export const overlayStyle = `
:host{all:initial;--accent:var(--color-primary,#b6c9a0);--ink:#eeeef1;--muted:#a1a1ac;--line:rgba(255,255,255,.09);font:13px/1.5 "Segoe UI","Microsoft YaHei",sans-serif;color:var(--ink);color-scheme:dark}
.canvas-shell{font:13px/1.5 "Segoe UI","Microsoft YaHei",sans-serif;color:var(--ink);color-scheme:dark}
.entry,.panel,.menu{-webkit-app-region:no-drag}
*{box-sizing:border-box} [hidden]{display:none!important} button,input,select{font:inherit} button{color:inherit;cursor:pointer} button:disabled,input:disabled,select:disabled{opacity:.45;cursor:default}
button{border:0;background:none} button:focus-visible,summary:focus-visible,select:focus-visible,input:focus-visible{outline:2px solid var(--accent);outline-offset:3px} button:hover{background:rgba(255,255,255,.07)}
svg{width:18px;height:18px;display:block;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}
.entry{position:fixed;right:10px;bottom:220px;width:34px;height:40px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.17);border-radius:12px 5px 5px 12px;background:rgba(36,37,42,.94);color:#e6e7eb;box-shadow:0 3px 14px #0003;touch-action:none;user-select:none;cursor:grab;z-index:2}
.entry[data-side=left]{border-radius:5px 12px 12px 5px}.entry:hover,.entry[aria-expanded=true]{background:#383a40;color:white;border-color:var(--accent)}.entry:active{cursor:grabbing}
.entry[data-intro=true]{width:74px;grid-template-columns:18px auto;gap:6px;padding:0 9px}.entry[data-intro=true]:after{content:"外观";font-size:11px;white-space:nowrap}
.panel{position:fixed;display:flex;flex-direction:column;width:400px;max-width:calc(100vw - 24px);max-height:min(720px,calc(100vh - 64px));border:1px solid rgba(255,255,255,.14);border-radius:18px;background:linear-gradient(150deg,rgba(46,47,54,.985),rgba(25,26,31,.985));box-shadow:0 20px 70px #0006,0 2px 10px #0003,inset 0 1px #ffffff08;overflow:hidden;animation:arrive .16s ease-out;z-index:3}
@keyframes arrive{from{opacity:0;transform:translateY(5px) scale(.985)}to{opacity:1;transform:none}}
header{display:flex;align-items:center;padding:20px 20px 13px;gap:10px;flex-shrink:0}.brand{width:30px;height:30px;display:grid;place-items:center;background:rgba(255,255,255,.055);border:1px solid var(--line);border-radius:10px;color:var(--accent)}h1{font-size:16px;font-weight:600;letter-spacing:.03em;margin:0}.sub{font-size:10px;letter-spacing:.2em;color:var(--muted)}.spacer{flex:1}.icon{width:28px;height:28px;display:grid;place-items:center;border-radius:7px;color:var(--muted)}
.content{min-height:0;overflow:auto;padding:0 20px 12px;overscroll-behavior:contain;scrollbar-width:thin;scrollbar-color:#ffffff25 transparent}.label{display:flex;align-items:center;gap:8px;margin:12px 0 10px;font-weight:600;font-size:12px}.label small{font-size:10px;font-weight:400;color:var(--muted);font-variant-numeric:tabular-nums}.text-button{font-size:11px;color:var(--muted);padding:4px 7px;border-radius:5px}.text-button:hover{color:var(--ink)}
.themes{display:flex;gap:9px;overflow-x:auto;padding:3px 3px 9px;margin:0 -3px;scrollbar-width:thin}.theme{flex:0 0 49px;padding:0;border-radius:9px;font-size:10px;color:var(--muted);background:none!important}.swatch{position:relative;display:block;height:33px;border-radius:8px;border:1px solid #ffffff18;overflow:hidden;margin-bottom:5px}.swatch:after{content:"";position:absolute;inset:9px 10px 9px 24px;border-radius:4px;background:var(--swatch-accent);box-shadow:-14px 4px 0 -3px #ffffff35}.theme[aria-pressed=true] .swatch{outline:2px solid var(--accent);outline-offset:2px}.theme[aria-pressed=true]{color:var(--ink)}.theme-name{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:49px}
.wallpaper-heading{border-top:1px solid var(--line);padding-top:14px;margin-top:7px}.library{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;max-height:242px;overflow:auto;padding:3px;margin:0 -3px;scrollbar-width:thin;scrollbar-color:#ffffff25 transparent;overscroll-behavior:contain}.tile{position:relative;padding:0;aspect-ratio:1.45;border-radius:9px;background:#ffffff07;overflow:hidden;border:1px solid #ffffff0b}.tile img,.tile canvas{width:100%;height:100%;object-fit:cover;display:block;transition:filter .15s}.tile:hover img,.tile:hover canvas{filter:brightness(1.12)}.tile[aria-pressed=true]{outline:2px solid var(--accent);outline-offset:1px}.tile[aria-pressed=true]:after{content:"✓";position:absolute;right:5px;bottom:5px;display:grid;place-items:center;width:19px;height:19px;border-radius:50%;background:#e9efdf;color:#24291d;font-size:12px;font-weight:bold;box-shadow:0 1px 5px #0006}.tile .broken{color:var(--muted);font-size:10px;padding:8px}.empty{grid-column:1/-1;padding:26px 14px;text-align:center;border:1px dashed #ffffff22;border-radius:10px;color:var(--muted);font-size:12px}.empty strong{display:block;color:var(--ink);font-size:13px;margin-bottom:5px}.current{font-size:10px;color:var(--muted);display:flex;gap:8px;align-items:center;margin:8px 0 0}.current span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1}.current button{flex-shrink:0}
.tuning{border-top:1px solid var(--line);margin-top:12px;padding-top:11px}.knob{display:grid;grid-template-columns:35px 1fr 43px;align-items:center;gap:12px;min-height:34px;font-size:11px;color:#c6c6d0}.knob output{text-align:right;font-size:10px;color:var(--muted);font-variant-numeric:tabular-nums}input[type=range]{appearance:none;width:100%;height:22px;margin:0;background:transparent;cursor:pointer;touch-action:none}input[type=range]::-webkit-slider-runnable-track{height:3px;border-radius:9px;background:linear-gradient(to right,var(--accent) var(--fill,0%),#ffffff19 var(--fill,0%))}input[type=range]::-webkit-slider-thumb{appearance:none;width:11px;height:11px;background:#e8e8ed;border:2px solid #e8e8ed;border-radius:50%;margin-top:-4px;box-shadow:0 1px 4px #0005}input[type=range]:hover::-webkit-slider-thumb{box-shadow:0 0 0 4px #ffffff10}
details{margin-top:7px}summary{list-style:none;cursor:pointer;color:var(--muted);font-size:11px;display:flex;align-items:center;justify-content:space-between;padding:5px 0}summary:after{content:"＋"}details[open] summary:after{content:"−"}select{background:#303139;color:var(--ink);border:1px solid var(--line);border-radius:5px;padding:4px 8px;max-width:160px}.select-row{display:flex;align-items:center;justify-content:space-between;font-size:11px;padding:8px 0}
footer{display:flex;gap:8px;align-items:center;min-height:37px;border-top:1px solid var(--line);padding:8px 20px;color:var(--muted);font-size:10px;flex-shrink:0}footer .dot{width:4px;height:4px;background:var(--accent);border-radius:50%;flex-shrink:0}#status{flex:1}kbd{font:9px/1.3 inherit;border:1px solid #ffffff17;border-radius:4px;padding:1px 4px;color:#9c9ca7}
.menu{position:fixed;z-index:4;background:#2d2e35;border:1px solid #ffffff20;box-shadow:0 8px 24px #0005;border-radius:10px;padding:5px;min-width:152px}.menu button{display:block;width:100%;text-align:left;font-size:12px;padding:8px 10px;border-radius:6px}.menu hr{border:0;border-top:1px solid var(--line);margin:4px}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
`;
